type conversion to isinstance
louisVottero/vtool pull request #292
Opened 2023-10-17 02:02 UTC by caterpillarAttack

This is roughly 20% faster and doesnt rely on an equality check under the hood. https://www.pylenin.com/blogs/type-vs-isinstance/#type-vs-isinstance

2023-10-17 04:37 UTC, caterpillarAttack commented on python/vtool/util.py
> +    if isinstance(variable, list) and sequence_type == tuple:
use is here

2023-10-17 04:37 UTC, caterpillarAttack commented on python/vtool/util.py
> +    if isinstance(variable, tuple) and sequence_type == list:
use is here

2023-10-17 04:47 UTC, caterpillarAttack commented on python/vtool/process_manager/ui_options.py
> +                    if widget_type is ProcessOptionGroup or widget_type is ProcessReferenceGroup:
use isinstance

2023-10-17 04:48 UTC, caterpillarAttack commented on python/vtool/process_manager/ui_options.py
> +            if type(self) is ProcessReferenceGroup:
use isinstance

2023-10-17 19:21 UTC, caterpillarAttack commented on python/vtool/process_manager/ui_options.py
> +                    if widget_type is ProcessOptionGroup or widget_type is ProcessReferenceGroup:
nevermind, its good as is.

2023-10-17 19:21 UTC, caterpillarAttack commented on python/vtool/process_manager/ui_options.py
> +            if type(self) is ProcessReferenceGroup:
nevermind, its good as is.

2023-10-18 20:21 UTC, louisVottero commented
This is doing something to skin weight import, will try to pinpoint it

2023-10-18 20:26 UTC, louisVottero commented on python/vtool/maya_lib/api.py
> -    if type(weights) == type(om.MDoubleArray()):
V: Error!	Traceback (most recent call last):	
V:		  File "E:/dev/git/vtool/python\vtool\util.py", line 76, in wrapper	
V:		    return_value = function(*args, **kwargs)	
V:		  File "E:/dev/git/vtool/python\vtool\data.py", line 1673, in import_data	
V:		    self._import_maya_data(filepath, selection)	
V:		  File "E:/dev/git/vtool/python\vtool\data.py", line 1323, in _import_maya_data	
V:		    result = self.import_skin_weights(folder_path, mesh, first = first)	
V:		  File "E:/dev/git/vtool/python\vtool\data.py", line 1568, in import_skin_weights	
V:		    maya_lib.api.set_skin_weights(skin_cluster, weight_array, 0)	
V:		  File "E:/dev/git/vtool/python\vtool\maya_lib\api.py", line 1837, in set_skin_weights	
V:		    if isinstance(weights, om.MDoubleArray()):	
V:		TypeError: isinstance() arg 2 must be a type or tuple of types

2023-10-18 20:30 UTC, louisVottero requested changes

2023-10-18 20:30 UTC, louisVottero commented on python/vtool/maya_lib/api.py
> -    if type(weights) == type(om.MDoubleArray()):
The error above I get from Maya when running the human body template
Maybe isinstance doesn't work on om.MDoubleArray()

2023-10-18 20:44 UTC, louisVottero approved these changes

2023-10-18 20:44 UTC, merged